export const RESET_LOGIN = "RESET_LOGIN";
export const LOGIN_TOKEN = "LOGIN_TOKEN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESETNEW_PASSWORD = "RESETNEW_PASSWORD";
export const RESETNEW_PASSWORD_ERROR = "RESETNEW_PASSWORD_ERROR";
export const OTPVERIFY_EMAIL = "OTPVERIFY_EMAIL";
export const OTPVERIFY_EMAIL_ERROR = "OTPVERIFY_EMAIL_ERROR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const GET_TENANT = "GET_TENANT";
export const RESET_TENANT = "RESET_TENANT";
export const GET_TENANT_LIST = "GET_TENANT_LIST";
export const CREATE_TENANT = "CREATE_TENANT";
export const DELETE_TENANT = "DELETE_TENANT";
export const UPDATE_TENANT = "UPDATE_TENANT";

export const GET_ACCOUNT = "GET_ACCOUNT";
export const RESET_ACCOUNT = "RESET_ACCOUNT";
export const GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";

export const GET_WF = "GET_WF";
export const RESET_WF = "RESET_WF";
export const GET_WF_LIST = "GET_WF_LIST";
export const CREATE_WF = "CREATE_WF";
export const DELETE_WF = "DELETE_WF";
export const UPDATE_WF = "UPDATE_WF";

export const CREATING_NODE = "CREATING_NODE";
export const UPDATING_NODE = "UPDATING_NODE";
export const UPDATE_NODE_STATUS = "UPDATE_NODE_STATUS";
export const UPDATE_NODE_REPORT = "UPDATE_NODE_REPORT";
export const CREATE_NODE = "CREATE_NODE";
export const UPDATE_NODE = "UPDATE_NODE";
export const RESTART_NODE = "RESTART_NODE";
export const GET_NODES = "GET_NODES";
export const DELETE_NODES = "DELETE_NODES";
export const GET_VIEW = "GET_VIEW";
export const UPDATE_VIEW = "UPDATE_VIEW";
export const GET_META = "GET_META";
export const SINGLESHOT = "SINGLESHOT";

export const GET_SIMULATION_LIST = "GET_SIMULATION_LIST";
export const CREATE_SIMULATION_VIEW = "CREATE_SIMULATION_VIEW";
export const DELETE_SIMULATION_VIEW = "DELETE_SIMULATION_VIEW";
export const CREATING_SIMULATION_NODE = "CREATING_SIMULATION_NODE";
export const CREATE_SIMULATION_NODE = "CREATE_SIMULATION_NODE";
export const UPDATE_SIMULATION_NODE = "UPDATE_SIMULATION_NODE";
export const GET_SIMULATION_NODES = "GET_SIMULATION_NODES";
export const DELETE_SIMULATION_NODES = "DELETE_SIMULATION_NODES";
export const SIMULATION_LOADING = "SIMULATION_LOADING";
export const GET_SIMULATION_VIEW = "GET_SIMULATION_VIEW";
export const UPDATE_SIMULATION_VIEW = "UPDATE_SIMULATION_VIEW";
export const RESET_SIMULATION_CONFIGURATION = "RESET_SIMULATION_CONFIGURATION";
export const CONFIG_SIMULATION_BUTTON = "CONFIG_SIMULATION_BUTTON";
export const GET_SIMULATION_EVENTS = "GET_SIMULATION_EVENTS";
export const RESET_CONFIGURATION = "RESET_CONFIGURATION";
export const CONFIG_BUTTON = "CONFIG_BUTTON";
export const GET_EVENTS = "GET_EVENTS";
export const UPDATE_EVENTS = "UPDATE_EVENTS";
export const GET_VERSIONS = "GET_VERSIONS";
export const DELETE_EDGE = "DELETE_EDGE";

export const RESET_DASHBOARD = "RESET_DASHBOARD";
export const GET_BUILD_REPORTS = "GET_BUILD_REPORTS";
export const GET_BUILD_DETAILS = "GET_BUILD_DETAILS";
export const GET_RECENT_BUILD_SUMMARY = "GET_RECENT_BUILD_SUMMARY";
export const GET_TOTAL_STATS = "GET_TOTAL_STATS";
export const GET_BUILD_TREND = "GET_BUILD_TREND";

export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECT_BUILDS = "GET_PROJECT_BUILDS";
export const GET_PROJECT_LIST = "GET_PROJECT_LIST";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const RESET_PROJECT = "RESET_PROJECT";
export const START_PROJECT_BUILDS = "START_PROJECT_BUILDS";
export const STOP_PROJECT_BUILDS = "STOP_PROJECT_BUILDS";
export const VERSION_CHANGE_PROJECT = "VERSION_CHANGE_PROJECT";

export const GET_TEST_SCENARIO_LIST = "GET_TEST_SCENARIO_LIST";
export const RESET_TEST_SCENARIO = "RESET_TEST_SCENARIO";
export const CREATE_TEST_SCENARIO = "CREATE_TEST_SCENARIO";
export const DELETE_TEST_SCENARIO = "DELETE_TEST_SCENARIO";
export const UPDATE_TEST_SCENARIO = "UPDATE_TEST_SCENARIO";
export const CLONE_TEST_SCENARIO = "CLONE_TEST_SCENARIO";
export const INSTALL_TEST_SCENARIO = "INSTALL_TEST_SCENARIO";
export const VERSION_CHANGE_TEST_SCENARIO = "VERSION_CHANGE_TEST_SCENARIO";
export const RUN_TEST_SCENARIO = "RUN_TEST_SCENARIO";

export const GET_TESTCASE_LIST = "GET_TESTCASE_LIST";
export const GET_TESTCASE = "GET_TESTCASE";
export const RESET_TESTCASE = "RESET_TESTCASE";
export const CREATE_TESTCASE = "CREATE_TESTCASE";
export const DELETE_TESTCASE = "DELETE_TESTCASE";
export const UPDATE_TESTCASE = "UPDATE_TESTCASE";
export const CLONE_TESTCASE = "CLONE_TESTCASE";
export const RUN_TESTCASE = "RUN_TESTCASE";

export const START_SIMULATION = "START_SIMULATION";
export const STOP_SIMULATION = "STOP_SIMULATION";

export const V1_GET_PROJECT_DATA = "V1_GET_PROJECT_DATA";
export const V1_SAVE_PROJECT = "V1_SAVE_PROJECT";
export const V1_CONFIG_CHANGE = "V1_CONFIG_CHANGE";
export const TEST_SEQUENCER = "TEST_SEQUENCER";
export const TEST_SEQUENCER_DELETE_EDGE = "TEST_SEQUENCER_DELETE_EDGE";

export const CONSOLE_LOG = "CONSOLE_LOG";
