version: "3.9"

services:
  vinashak-api:
    image: vinashak/api:latest
    container_name: vinashak-api
    build:
      context: ./orchestrator
    environment:
      - SELENIUM_GRID_URL=http://10.27.21.38:4444
      - DATABASE_HOST=10.27.21.38
      - REDIS_HOST=10.27.21.38
      - LOG_DIR=/app/logs
      - LOG_LEVEL=all
      - PORT=80
    volumes:
      - ./data/vinashak/:/app/logs
    networks:
      - vinashak

  vinashak-studio:
    image: vinashak/studio:latest
    container_name: vinashak-studio
    build: .
    links:
      - vinashak-api
    depends_on:
      vinashak-api:
        condition: service_started
    ports:
      - 80:80
    networks:
      - vinashak

networks:
  vinashak:
    driver: bridge
