version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: vinashak-cache
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: "--requirepass S3cret"
    volumes:
      - ./data/redis/:/data
    networks:
      - vinashak

  database:
    image: mysql:5.7
    container_name: vinashak-db
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./data/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_DATABASE: automation
      MYSQL_USER: automation
      MYSQL_PASSWORD: S3cret
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
    networks:
      - vinashak

  vinashak-api:
    image: vinashak/api:latest
    container_name: vinashak-api
    build:
      context: ./orchestrator
    links:
      - database
      - redis
      - selenium-router
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      selenium-router:
        condition: service_started
    environment:
      - SELENIUM_GRID_URL=http://selenium-router:4444
      - DATABASE_HOST=database
      - REDIS_HOST=redis
      - JWT_TOKEN_EXPIRY=1d
      - LOG_DIR=/app/logs
      - LOG_LEVEL=all
      - PORT=80
    volumes:
      - ./data/vinashak/:/app/logs
    networks:
      - vinashak

  vinashak-studio:
    image: vinashak/studio:latest
    container_name: vinashak-studio
    build: .
    links:
      - vinashak-api
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 80:80
    networks:
      - vinashak

  selenium-event-bus:
    image: selenium/event-bus:4.4.0-20220831
    container_name: selenium-event-bus
    networks:
      - vinashak

  selenium-sessions:
    image: selenium/sessions:4.4.0-20220831
    container_name: selenium-sessions
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - vinashak

  selenium-session-queue:
    image: selenium/session-queue:4.4.0-20220831
    container_name: selenium-session-queue
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - vinashak

  selenium-distributor:
    image: selenium/distributor:4.4.0-20220831
    container_name: selenium-distributor
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
    networks:
      - vinashak

  selenium-router:
    image: selenium/router:4.4.0-20220831
    container_name: selenium-router
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
    networks:
      - vinashak

  chrome:
    image: selenium/node-chrome:4.4.0-20220831
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - vinashak

networks:
  vinashak:
    driver: bridge
