version: "3.9"

services:
  redis:
    image: redis
    container_name: vinashak-cache
    ports:
      - 6379:6379
    command: >
      --requirepass S3cret
    volumes:
      - ./data/redis/:/etc/redis/

  database:
    image: mysql:5.7
    container_name: vinashak-db
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./data/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_DATABASE: automation
      MYSQL_USER: automation
      MYSQL_PASSWORD: S3cret
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10

  vinashak-orchestrator:
    image: vinashak/orchestrator:latest
    container_name: vinashak-orchestrator
    build: ./orchestrator
    links:
      - database
      - redis
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_HOST=database
      - REDIS_HOST=redis
      - LOG_DIR=/app/logs
    volumes:
      - ./data/vinashak/:/app/logs

  vinashak-client:
    image: vinashak/client:latest
    container_name: vinashak-client
    build: .
    stdin_open: true
    links:
      - vinashak-orchestrator
    ports:
      - 80:80
    depends_on:
      vinashak-orchestrator:
        condition: service_started

  vinashak-agent:
    image: vinashak/agent:latest
    container_name: vinashak-agent
    build: ./agent
    links:
      - vinashak-orchestrator
      - selenium-router
    depends_on:
      vinashak-orchestrator:
        condition: service_started
      selenium-router:
        condition: service_started
    environment:
      - SERVER_URL=http://vinashak-orchestrator
      - SELENIUM_GRID_URL=http://selenium-router
      - LOG_DIR=/app/logs
    volumes:
      - ./data/vinashak/:/app/logs

  selenium-event-bus:
    image: selenium/event-bus:4.4.0-20220831
    container_name: selenium-event-bus
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"

  selenium-sessions:
    image: selenium/sessions:4.4.0-20220831
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-session-queue:
    image: selenium/session-queue:4.4.0-20220831
    container_name: selenium-session-queue
    ports:
      - "5559:5559"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-distributor:
    image: selenium/distributor:4.4.0-20220831
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  selenium-router:
    image: selenium/router:4.4.0-20220831
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  chrome:
    image: selenium/node-chrome:4.4.0-20220831
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.4.0-20220831
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.4.0-20220831
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
