version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: vinashak-cache
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: "--requirepass S3cret"
    volumes:
      - ./data/redis/:/data

  database:
    image: mysql:5.7
    container_name: vinashak-db
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./data/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_DATABASE: automation
      MYSQL_USER: automation
      MYSQL_PASSWORD: S3cret
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10

  vinashak-orchestrator:
    image: vinashak/orchestrator:latest
    container_name: vinashak-orchestrator
    build: ./orchestrator
    links:
      - database
      - redis
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_HOST=database
      - REDIS_HOST=redis
      - LOG_DIR=/app/logs
      - LOG_LEVEL=all
      - GRPC_PORT=50000
    volumes:
      - ./data/vinashak/:/app/logs

  vinashak-client:
    image: vinashak/client:latest
    container_name: vinashak-client
    build: .
    stdin_open: true
    links:
      - vinashak-orchestrator
    ports:
      - 80:80
    depends_on:
      vinashak-orchestrator:
        condition: service_started

  vinashak-agent:
    image: vinashak/agent:latest
    container_name: vinashak-agent
    build: ./agent
    links:
      - vinashak-orchestrator
      - redis
    depends_on:
      vinashak-orchestrator:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - SERVER_URL=http://vinashak-orchestrator
      - GRPC_SERVER_ENDPOINT=vinashak-orchestrator:50000
      - SELENIUM_GRID_URL=http://kontronbng141:4444
      - LOG_DIR=/app/logs
      - LOG_LEVEL=all
      - REDIS_HOST=redis
    volumes:
      - ./data/vinashak/:/app/logs
