services:
  leap-cache:
    image: redis/redis-stack-server:latest
    container_name: leap-cache
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: "--requirepass S3cret"
    volumes:
      - ./data/redis/:/data
    networks:
      leap-network:
        ipv4_address: 10.5.0.5

  leap-database:
    image: postgres:latest
    container_name: leap-database
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgres/
    environment:
      POSTGRES_ROOT_USER: root
      POSTGRES_ROOT_PASSWORD: S3cret
      POSTGRES_DB: automation
      POSTGRESL_USER: automation
      POSTGRES_PASSWORD: S3cret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 20s
      retries: 10
    networks:
      leap-network:
        ipv4_address: 10.5.0.6

  leap-studio:
    image: leapworkflow/studio:latest
    container_name: leap-studio
    build: .
    links:
      - leap-database
      - leap-cache
      - selenium-router
    depends_on:
      leap-database:
        condition: service_healthy
      leap-cache:
        condition: service_started
      selenium-router:
        condition: service_started
    environment:
      - SELENIUM_GRID_URL=http://selenium-router:4444
      - DATABASE_HOST=leap-database
      - REDIS_HOST=leap-cache
      - JWT_TOKEN_EXPIRY=1d
      - LOG_DIR=/app/logs
      - LOG_LEVEL=all
      - PORT=9004
    volumes:
      - ./data/leap/:/app/logs
      - ./data/leap/nginx:/var/log/nginx
    ports:
      - 80:80
    networks:
      leap-network:
        ipv4_address: 10.5.0.9

  selenium-event-bus:
    image: selenium/event-bus:latest
    container_name: selenium-event-bus
    networks:
      leap-network:
        ipv4_address: 10.5.0.10

  selenium-sessions:
    image: selenium/sessions:latest
    container_name: selenium-sessions
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      leap-network:
        ipv4_address: 10.5.0.11

  selenium-session-queue:
    image: selenium/session-queue:latest
    container_name: selenium-session-queue
    networks:
      leap-network:
        ipv4_address: 10.5.0.12

  selenium-distributor:
    image: selenium/distributor:latest
    container_name: selenium-distributor
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
    networks:
      leap-network:
        ipv4_address: 10.5.0.13

  selenium-router:
    image: selenium/router:latest
    container_name: selenium-router
    ports:
      - 4444:4444
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
    networks:
      leap-network:
        ipv4_address: 10.5.0.14

  selenium-chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    container_name: selenium-chrome
    volumes:
      - ./data/assets:/opt/selenium/assets
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - VNC_NO_PASSWORD=1
    networks:
      leap-network:
        ipv4_address: 10.5.0.15

networks:
  leap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
