services:
  vinashak-cache:
    image: redis/redis-stack-server:latest
    container_name: vinashak-cache
    ports:
      - 6379:6379
    environment:
      REDIS_ARGS: "--requirepass S3cret"
    volumes:
      - ./data/redis/:/data
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.5

  vinashak-database:
    image: mysql:latest
    container_name: vinashak-database
    ports:
      - 3306:3306
    #command: --init-file /data/application/init.sql
    command: --sort_buffer_size=512K
    volumes:
      #- ./init.sql:/data/application/init.sql
      - ./data/mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_DATABASE: automation
      MYSQL_USER: automation
      MYSQL_PASSWORD: S3cret
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.6

  vinashak-studio:
    image: vinashakstudio/vinashak-studio:latest
    container_name: vinashak-studio
    build: .
    links:
      - vinashak-database
      - vinashak-cache
      - selenium-router
    depends_on:
      vinashak-database:
        condition: service_healthy
      vinashak-cache:
        condition: service_started
      selenium-router:
        condition: service_started
    environment:
      - SELENIUM_GRID_URL=http://selenium-router:4444
      - DATABASE_HOST=vinashak-database
      - REDIS_HOST=vinashak-cache
      - JWT_TOKEN_EXPIRY=1d
      - LOG_DIR=/app/logs
      - LOG_LEVEL=all
      - PORT=8080
      - DATABASE_LOGGING=true
    volumes:
      - ./data/vinashak/:/app/logs
      - ./data/vinashak/nginx:/var/log/nginx
    ports:
      - 80:80
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.9

  selenium-event-bus:
    image: selenium/event-bus:latest
    container_name: selenium-event-bus
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.10

  selenium-sessions:
    image: selenium/sessions:latest
    container_name: selenium-sessions
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.11

  selenium-session-queue:
    image: selenium/session-queue:latest
    container_name: selenium-session-queue
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.12

  selenium-distributor:
    image: selenium/distributor:latest
    container_name: selenium-distributor
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.13

  selenium-router:
    image: selenium/router:latest
    container_name: selenium-router
    ports:
      - 4444:4444
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.14

  selenium-chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    container_name: selenium-chrome
    volumes:
      - ./data/assets:/opt/selenium/assets
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - VNC_NO_PASSWORD=1
    networks:
      vinashak-network:
        ipv4_address: 10.5.0.15

networks:
  vinashak-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
