exports.STATUSCODES = Object.freeze({
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  ERROR: "ERROR"
});

exports.TASK_TYPES = Object.freeze({
  START_TASK: "START_TASK",
  TIMER_TASK: "TIMER_TASK",
  CASE_TASK: "CASE_TASK",
  SCENARIO_TASK: "SCENARIO_TASK",
  STOP_TASK: "STOP_TASK"
});
